import {COLORS,createDraft,weave,fabricSVG,escapeXML,mod,validateDraft,resizeDraft,chartSVG} from './model.js';
const $=s=>document.querySelector(s);let draft=createDraft(),activeColor=COLORS[0].hex,showBack=false;
function render(){
$('#card-type').value=draft.holes;$('#card-count').value=draft.cards;$('#pick-count').value=draft.picks;$('#draft-name').value=draft.name;
$('#thread-count').textContent=`${draft.cards*draft.holes} threads`;$('#preview-size').textContent=`${draft.cards} tablets · ${draft.picks} picks`;$('#draft-stats').textContent=`${draft.holes}-hole cards / ${draft.cards*draft.holes} warp threads`;
$('#ruler-middle').textContent=Math.ceil(draft.picks/2);$('#ruler-end').textContent=draft.picks;
$('#palette').innerHTML=draft.colors.map(c=>`<button class="swatch" style="--swatch:${c.hex};--check:${c.hex==='#f0e3c6'?'#615c4c':'#fff'}" aria-label="Select ${escapeXML(c.name)}" aria-pressed="${activeColor===c.hex}" data-color="${c.hex}" title="${escapeXML(c.name)}"></button>`).join('');
const pts=Array.from({length:draft.holes},(_,h)=>{const a=-Math.PI/2+Math.PI/draft.holes+h*2*Math.PI/draft.holes;return [70+47*Math.cos(a),66+47*Math.sin(a)];});
$('#card-illustration').innerHTML=`<svg viewBox="0 0 140 132" aria-label="${draft.holes}-hole tablet diagram"><polygon points="${pts.map(p=>p.join(',')).join(' ')}" fill="#f6eddf" stroke="#dacdbc" stroke-width="1.5" stroke-linejoin="round"/>${pts.map(([x,y],h)=>`<circle cx="${70+(x-70)*.68}" cy="${66+(y-66)*.68}" r="4.5" fill="${draft.threads[0][h]}" stroke="#d2bfa5" stroke-width="1"/><text x="${70+(x-70)*1.22}" y="${70+(y-66)*1.22}" text-anchor="middle" fill="#969083" font-size="10">${String.fromCharCode(65+h)}</text>`).join('')}<text x="70" y="70" text-anchor="middle" fill="#b5a996" font-size="16" font-family="serif">${draft.holes}</text></svg>`;
$('#rotation-label').textContent=`${draft.holes===4?'¼':`1/${draft.holes}`} turn per pick`;$('.card-caption span:last-child').textContent=`A–${String.fromCharCode(64+draft.holes)}`;
let threading='<span></span>'+Array.from({length:draft.cards},(_,c)=>`<span class="chart-label">${c+1}</span>`).join('');for(let h=0;h<draft.holes;h++){threading+=`<span class="chart-label">${String.fromCharCode(65+h)}</span>`;for(let c=0;c<draft.cards;c++)threading+=`<button class="hole-cell" data-card="${c}" data-hole="${h}" style="--thread:${draft.threads[c][h]}" aria-label="Tablet ${c+1}, hole ${String.fromCharCode(65+h)}, ${draft.threads[c][h]}" title="Tablet ${c+1} · Hole ${String.fromCharCode(65+h)}"></button>`;}
threading+='<span class="chart-label">↗</span>'+draft.slants.map((s,c)=>`<button class="slant-cell" data-card="${c}" data-slant="${s}" aria-label="Tablet ${c+1}: ${s} threading. Click to flip">${s}</button>`).join('');$('#thread-chart').style.setProperty('--cards',draft.cards);$('#thread-chart').innerHTML=threading;
let turns='<span class="chart-label column-head">↓</span>'+Array.from({length:draft.cards},(_,c)=>`<span class="chart-label column-head">${c+1}</span>`).join('');for(let r=0;r<draft.picks;r++){turns+=`<button class="pick-label" data-pick="${r}" title="Reverse all tablets in pick ${r+1}" aria-label="Reverse all tablets in pick ${r+1}">${String(r+1).padStart(2,'0')}</button>`;for(let c=0;c<draft.cards;c++)turns+=`<button class="turn-cell" data-card="${c}" data-pick="${r}" data-dir="${draft.turns[r][c]}" aria-label="Pick ${r+1}, tablet ${c+1}: ${draft.turns[r][c]==='F'?'forward':'backward'}. Click to reverse">${draft.turns[r][c]}</button>`;}$('#turn-chart').style.setProperty('--cards',draft.cards);$('#turn-chart').innerHTML=turns;
$('#woven-preview').innerHTML=fabricSVG(draft,showBack);$('#preview-face').textContent=showBack?'Back of band':'Front of band';updateStateLabels();
}
let history=[],future=[],dirty=false,painting=false,paintCheckpoint=false,toastTimer;
const snapshot=()=>JSON.stringify(draft);
function checkpoint(){history.push(snapshot());if(history.length>80)history.shift();future=[];dirty=true;}
function updateStateLabels(){
$('#undo').disabled=!history.length;$('#redo').disabled=!future.length;
const color=draft.colors.find(c=>c.hex===activeColor);$('#active-color-name').textContent=color?.name||activeColor;$('.mini-swatch').style.background=activeColor;
const rows=draft.turns.map(r=>r.every(x=>x===r[0])?r[0]:'mixed');
let repeat='Custom turns';if(rows.every(r=>r==='F'))repeat='All forward';else if(rows.every(r=>r==='B'))repeat='All backward';else if(!rows.includes('mixed')){let period=rows.length;for(let p=1;p<=rows.length/2;p++){if(rows.every((v,i)=>v===rows[i%p])){period=p;break;}}const runs=[];for(const d of rows.slice(0,period)){if(runs.at(-1)?.d===d)runs.at(-1).n++;else runs.push({d,n:1});}if(runs.length<=4)repeat=runs.map(r=>`${r.n}${r.d}`).join(' / ');}
$('#preview-repeat').textContent=repeat;$('#status-message').textContent=dirty?'Draft changed · Save a copy to keep your work.':'Ready to weave something good.';
$('#apply-preset').title='Replace threading and turns with this starting pattern. Undo is available.';
}
function notice(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3800);}
function change(action,message){checkpoint();action();render();if(message)notice(message);}
function undo(){if(!history.length)return;future.push(snapshot());draft=JSON.parse(history.pop());dirty=true;render();}
function redo(){if(!future.length)return;history.push(snapshot());draft=JSON.parse(future.pop());dirty=true;render();}
function resize(values){try{const next=resizeDraft(draft,values);if(JSON.stringify(next)===snapshot())return;change(()=>draft=next,values.holes?'Card type updated. Existing hole colors are kept; extra holes start natural.':undefined);}catch(e){notice(e.message);render();}}
function setColor(hex){activeColor=hex;render();}
function paint(cell){const c=Number(cell.dataset.card),h=Number(cell.dataset.hole);if(draft.threads[c][h]===activeColor)return;if(!paintCheckpoint){checkpoint();paintCheckpoint=true;}draft.threads[c][h]=activeColor;if(c===0)$('#card-illustration').querySelectorAll('circle')[h].setAttribute('fill',activeColor);cell.style.setProperty('--thread',activeColor);cell.setAttribute('aria-label',`Tablet ${c+1}, hole ${String.fromCharCode(65+h)}, ${activeColor}`);$('#woven-preview').innerHTML=fabricSVG(draft);updateStateLabels();}
$('#palette').addEventListener('click',e=>{const b=e.target.closest('[data-color]');if(b)setColor(b.dataset.color);});
$('#custom-color').addEventListener('change',e=>{const hex=e.target.value.toLowerCase();if(draft.colors.some(c=>c.hex===hex)){setColor(hex);return;}if(draft.colors.length>=24){notice('The palette supports up to 24 colors. Select an existing color.');return;}change(()=>{draft.colors.push({name:`Custom ${hex}`,hex});activeColor=hex;});});
$('#thread-chart').addEventListener('pointerdown',e=>{const cell=e.target.closest('.hole-cell');if(!cell||e.button!==0||e.pointerType==='touch')return;e.preventDefault();painting=true;paintCheckpoint=false;cell.focus({preventScroll:true});paint(cell);});
$('#thread-chart').addEventListener('pointerover',e=>{if(painting&&e.buttons===1){const cell=e.target.closest('.hole-cell');if(cell)paint(cell);}});
document.addEventListener('pointerup',()=>{if(painting){painting=false;paintCheckpoint=false;}});
$('#thread-chart').addEventListener('click',e=>{const hole=e.target.closest('.hole-cell');if(hole){paintCheckpoint=false;paint(hole);paintCheckpoint=false;return;}const cell=e.target.closest('.slant-cell');if(cell){const c=Number(cell.dataset.card);change(()=>draft.slants[c]=draft.slants[c]==='S'?'Z':'S');$(`.slant-cell[data-card="${c}"]`).focus({preventScroll:true});}});
$('#turn-chart').addEventListener('click',e=>{const cell=e.target.closest('.turn-cell'),row=e.target.closest('.pick-label');if(cell){const r=Number(cell.dataset.pick),c=Number(cell.dataset.card);change(()=>draft.turns[r][c]=draft.turns[r][c]==='F'?'B':'F');$(`.turn-cell[data-pick="${r}"][data-card="${c}"]`).focus({preventScroll:true});}else if(row){const r=Number(row.dataset.pick);change(()=>draft.turns[r]=draft.turns[r].map(d=>d==='F'?'B':'F'));$(`.pick-label[data-pick="${r}"]`).focus({preventScroll:true});}});
function applyRepeat(f,b){if(!Number.isInteger(f)||!Number.isInteger(b)||f<0||b<0||f>32||b>32||f+b===0)throw new Error('Use 0–32 turns in each direction, with at least one turn.');change(()=>{draft.turns=Array.from({length:draft.picks},(_,r)=>Array(draft.cards).fill(r%(f+b)<f?'F':'B'));},`Applied ${f} forward / ${b} backward turns.`);}
$('#apply-repeat').addEventListener('click',()=>{try{applyRepeat(Number($('#forward-count').value),Number($('#backward-count').value));}catch(e){notice(e.message);}});
$('#all-forward').addEventListener('click',()=>{applyRepeat(draft.holes,0);$('#forward-count').value=draft.holes;$('#backward-count').value=0;});
for(const [selector,key] of [['#card-count','cards'],['#pick-count','picks']])$(selector).addEventListener('input',e=>{if(e.target.value!==''&&e.target.validity.valid)resize({[key]:Number(e.target.value)});});
$('#card-type').addEventListener('change',e=>resize({holes:Number(e.target.value)}));$('#card-count').addEventListener('change',e=>resize({cards:Number(e.target.value)}));$('#pick-count').addEventListener('change',e=>resize({picks:Number(e.target.value)}));
document.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>{const [key,step]=b.dataset.step.split(':');resize({[key]:Math.max(key==='cards'?2:4,Math.min(key==='cards'?48:160,draft[key]+Number(step)))});}));
$('#apply-preset').addEventListener('click',()=>{const preset=$('#preset').value;change(()=>{draft=createDraft(draft.holes,draft.cards,draft.picks,preset);activeColor=COLORS[0].hex;},'Starting pattern applied. Undo restores your previous draft.');$('#forward-count').value=draft.holes;$('#backward-count').value=['diamond','blank'].includes(preset)?draft.holes:0;});
let editingName=false;
$('#draft-name').addEventListener('focus',()=>editingName=false);
$('#draft-name').addEventListener('input',e=>{if(!editingName){checkpoint();editingName=true;}draft.name=e.target.value||'Untitled pattern';updateStateLabels();});
$('#draft-name').addEventListener('blur',e=>{draft.name=e.target.value.trim()||'Untitled pattern';e.target.value=draft.name;});
$('#undo').addEventListener('click',undo);$('#redo').addEventListener('click',redo);
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'&&!['INPUT','TEXTAREA'].includes(e.target.tagName)){e.preventDefault();e.shiftKey?redo():undo();}const cell=e.target.closest('.hole-cell,.turn-cell');if(!cell)return;const offset={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(!offset)return;e.preventDefault();const isHole=cell.classList.contains('hole-cell'),key=isHole?'hole':'pick',c=Math.max(0,Math.min(draft.cards-1,Number(cell.dataset.card)+offset[0])),r=Math.max(0,Math.min((isHole?draft.holes:draft.picks)-1,Number(cell.dataset[key])+offset[1]));$(`.${isHole?'hole-cell':'turn-cell'}[data-card="${c}"][data-${key}="${r}"]`).focus();});
$('#help-button').addEventListener('click',()=>$('#help-dialog').showModal());$('[data-close]').addEventListener('click',()=>$('#help-dialog').close());$('#help-dialog').addEventListener('click',e=>{if(e.target===$('#help-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
function download(content,type,extension){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(draft.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'weaving-draft')+extension;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
$('#save-button').addEventListener('click',()=>{download(JSON.stringify(draft,null,2),'application/json','.json');dirty=false;updateStateLabels();$('#status-message').textContent='Draft downloaded · Open the file here to keep editing.';notice('Editable draft downloaded.');});
$('#open-button').addEventListener('click',()=>$('#file-input').click());$('#file-input').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2_000_000)throw new Error('Choose a draft file smaller than 2 MB.');const next=validateDraft(JSON.parse(await file.text()));change(()=>{draft=next;activeColor=draft.colors[0].hex;},'Draft opened. Your previous draft is available with Undo.');}catch(error){notice(error instanceof SyntaxError?'This file is not valid JSON. Open a draft saved from Turn.':error.message);}finally{e.target.value='';}});
$('#export-svg').addEventListener('click',()=>{download(chartSVG(draft),'image/svg+xml','.svg');notice('Threading chart, turning plan, and woven preview exported.');});
function preparePrint(){let sheet=$('#print-sheet');if(!sheet){sheet=document.createElement('section');sheet.id='print-sheet';document.body.append(sheet);}sheet.innerHTML=Array.from({length:Math.ceil(draft.picks/28)},(_,i)=>`<div class="${i?'print-page':''}">${chartSVG(draft,{start:i*28,end:Math.min((i+1)*28,draft.picks),includeThreading:i===0,includePreview:i===0})}</div>`).join('');}
$('#print-button').addEventListener('click',()=>{preparePrint();window.print();});window.addEventListener('beforeprint',preparePrint);window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
render();
const context=document.modelContext;
if(context?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const register=tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
register({name:'read_weaving_draft',title:'Read weaving draft',description:'Read the current tablet weaving draft, including hole colors, threading, and turns.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(){return JSON.parse(snapshot());}});
register({name:'configure_weaving_draft',title:'Configure weaving draft',description:'Resize the current draft while retaining existing colors and turns. Added holes use natural thread.',inputSchema:{type:'object',properties:{holes:{type:'integer',minimum:3,maximum:8},cards:{type:'integer',minimum:2,maximum:48},picks:{type:'integer',minimum:4,maximum:160}},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['holes','cards','picks'].includes(k)))throw new Error('Provide holes, cards, or picks.');const next=resizeDraft(draft,input);change(()=>draft=next);return {holes:draft.holes,cards:draft.cards,picks:draft.picks};}});
register({name:'apply_turning_repeat',title:'Apply turning repeat',description:'Replace all turning instructions with repeating forward then backward turns.',inputSchema:{type:'object',properties:{forward:{type:'integer',minimum:0,maximum:32},backward:{type:'integer',minimum:0,maximum:32}},required:['forward','backward'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).some(k=>!['forward','backward'].includes(k)))throw new Error('Provide forward and backward turn counts.');applyRepeat(input.forward,input.backward);$('#forward-count').value=input.forward;$('#backward-count').value=input.backward;return {picks:draft.picks,forward:input.forward,backward:input.backward};}});
}
